spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz
    username: postgres
    password: 2@5a!3b2
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10 # Adjust as per your application's needs
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true # Set to false in production
    properties:
      hibernate:
        format_sql: true

